// Automatically generated by MockGen. DO NOT EDIT!
// Source: sample.go

package mock_sample

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of writer interface
type Mockwriter struct {
	ctrl     *gomock.Controller
	recorder *_MockwriterRecorder
}

// Recorder for Mockwriter (not exported)
type _MockwriterRecorder struct {
	mock *Mockwriter
}

func NewMockwriter(ctrl *gomock.Controller) *Mockwriter {
	mock := &Mockwriter{ctrl: ctrl}
	mock.recorder = &_MockwriterRecorder{mock}
	return mock
}

func (_m *Mockwriter) EXPECT() *_MockwriterRecorder {
	return _m.recorder
}

func (_m *Mockwriter) Write(_param0 []byte) (int, error) {
	ret := _m.ctrl.Call(_m, "Write", _param0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockwriterRecorder) Write(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Write", arg0)
}
