// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

/*
Package cache is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	CacheRequest
	CacheReply
*/
package cache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type CacheRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CacheRequest) Reset()                    { *m = CacheRequest{} }
func (m *CacheRequest) String() string            { return proto.CompactTextString(m) }
func (*CacheRequest) ProtoMessage()               {}
func (*CacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CacheRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// The response message containing the greetings
type CacheReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *CacheReply) Reset()                    { *m = CacheReply{} }
func (m *CacheReply) String() string            { return proto.CompactTextString(m) }
func (*CacheReply) ProtoMessage()               {}
func (*CacheReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CacheReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CacheRequest)(nil), "cache.CacheRequest")
	proto.RegisterType((*CacheReply)(nil), "cache.CacheReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	// Sends a greeting
	Get(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheReply, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheReply, error) {
	out := new(CacheReply)
	err := grpc.Invoke(ctx, "/cache.Cache/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheServer interface {
	// Sends a greeting
	Get(context.Context, *CacheRequest) (*CacheReply, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*CacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cache.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe4, 0xb8, 0x78, 0x9c,
	0x41, 0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x15, 0x2e, 0x2e, 0xa8, 0x7c, 0x41,
	0x4e, 0xa5, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0x54, 0x05, 0x94, 0x67,
	0x64, 0xc1, 0xc5, 0x0a, 0x56, 0x25, 0xa4, 0xcf, 0xc5, 0xec, 0x9e, 0x5a, 0x22, 0x24, 0xac, 0x07,
	0xb1, 0x0a, 0xd9, 0x68, 0x29, 0x41, 0x54, 0xc1, 0x82, 0x9c, 0x4a, 0x25, 0x06, 0x27, 0x59, 0x2e,
	0xde, 0xcc, 0x7c, 0xbd, 0xf4, 0xa2, 0x82, 0x64, 0x88, 0xac, 0x13, 0x17, 0x98, 0x0a, 0x00, 0xb9,
	0x31, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x58, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x6a,
	0x97, 0xac, 0xbb, 0x00, 0x00, 0x00,
}
