// Automatically generated by MockGen. DO NOT EDIT!
// Source: sample.go

package mock_sample

import (
	gomock "github.com/golang/mock/gomock"
)

type MockSample struct {
	ctrl  *gomock.Controller
	recorder  *_MockSampleRecorder
}

type _MockSampleRecorder struct {
	mock *MockSample
}

type NewMockSample(ctrl *gomock.Controller) {
	mock := &MockSample{ctrl: ctrl}
	mock.recorder = &_MockSampleRecorder{mock}
	return mock
}

func (_m *MockSample) EXPECT() *_MockSampleRecorder {
	return _m.recoder
}

func (_m *MockSample) Method(str string) int {
	ret := _m.ctrl.Call(_m, "Method", str)
	ret0 := ret[0].(int)
	return ret0
}

func (_mr *_MockSampleRecorder) Method(arg0 interface{}) *gomock.Call {
	return _m.mock.ctrl.RecordCall(_mr.mock, "Method", arg0)
}